name: Deploy via FTP

on:
  push:
    branches:
      - main  # срабатывает после мёржа PR в main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужно для корректной работы с историей

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/jira.egodev1.info/  # укажи целевую директорию на сервере
          local-dir: ./              # какие локальные файлы загружать (по умолчанию — всё)
